"""Niro IR is a strongly typed, SSA-based representation composed of types,
values, program structure, operations, literals, and attributes.

You can construct programs with [`niro.builder.ModuleBuilder`][].
"""

from niro.ir import infer
from niro.ir.accessors import (
    BlockArgument,
    Definition,
    OpResult,
    Use,
    get_definition,
    get_operands,
    get_parent_block,
    get_regions,
    get_results,
    iter_blocks,
    iter_defined_values,
    iter_ops,
    iter_uses,
)
from niro.ir.data import AttributeName, Attributes, AttributeValue, Literal
from niro.ir.ops import (
    Add,
    Call,
    Const,
    GetGlobal,
    If,
    MatMul,
    Mul,
    Op,
    Return,
    Transpose,
    UnknownOp,
    Yield,
)
from niro.ir.program import (
    Block,
    Function,
    FunctionType,
    Global,
    Module,
    Region,
    SymbolName,
    VerifiedModule,
)
from niro.ir.types import Dimension, ScalarType, Shape, TensorType, Type
from niro.ir.values import Value, ValueId, ValueSupply

__all__ = [
    "Add",
    "AttributeName",
    "AttributeValue",
    "Attributes",
    "Block",
    "BlockArgument",
    "Call",
    "Const",
    "Definition",
    "Dimension",
    "Function",
    "FunctionType",
    "GetGlobal",
    "Global",
    "If",
    "Literal",
    "MatMul",
    "Module",
    "Mul",
    "Op",
    "OpResult",
    "Region",
    "Return",
    "ScalarType",
    "Shape",
    "SymbolName",
    "TensorType",
    "Transpose",
    "Type",
    "UnknownOp",
    "Use",
    "Value",
    "ValueId",
    "ValueSupply",
    "VerifiedModule",
    "Yield",
    "get_definition",
    "get_operands",
    "get_parent_block",
    "get_regions",
    "get_results",
    "infer",
    "iter_blocks",
    "iter_defined_values",
    "iter_ops",
    "iter_uses",
]
