"""Niro IR is a strongly typed, SSA-based representation composed of types,
values, program structure, operations, literals, and attributes.
"""

from niro.ir.data import AttributeName, Attributes, AttributeValue, Literal
from niro.ir.ops import (
    Add,
    Call,
    Const,
    GetGlobal,
    If,
    MatMul,
    Mul,
    Op,
    Return,
    Transpose,
    UnknownOp,
    Yield,
)
from niro.ir.program import (
    Block,
    Function,
    FunctionType,
    Global,
    Module,
    Region,
    SymbolName,
)
from niro.ir.types import Dimension, ScalarType, Shape, TensorType, Type
from niro.ir.values import Value, ValueId
from niro.ir.verify import (
    VerificationError,
    check_attribute_name,
    check_block_arguments,
    check_call_signature,
    check_function_signature,
    check_function_type,
    check_global,
    check_op,
    check_symbol_available,
    check_symbol_name,
    check_tensor_type,
    check_terminator,
    check_type,
    check_value,
    matmul_result_type,
    transpose_result_type,
    verify,
)

__all__ = [
    "Add",
    "AttributeName",
    "AttributeValue",
    "Attributes",
    "Block",
    "Call",
    "Const",
    "Dimension",
    "Function",
    "FunctionType",
    "GetGlobal",
    "Global",
    "If",
    "Literal",
    "MatMul",
    "Module",
    "Mul",
    "Op",
    "Region",
    "Return",
    "ScalarType",
    "Shape",
    "SymbolName",
    "TensorType",
    "Transpose",
    "Type",
    "UnknownOp",
    "Value",
    "ValueId",
    "VerificationError",
    "Yield",
    "check_attribute_name",
    "check_block_arguments",
    "check_call_signature",
    "check_function_signature",
    "check_function_type",
    "check_global",
    "check_op",
    "check_symbol_available",
    "check_symbol_name",
    "check_tensor_type",
    "check_terminator",
    "check_type",
    "check_value",
    "matmul_result_type",
    "transpose_result_type",
    "verify",
]
