"""Niro IR is a strongly typed, SSA-based representation composed of types,
values, program structure, operations, literals, and attributes.
"""

from niro.ir.data import AttributeName, Attributes, AttributeValue, Literal
from niro.ir.ops import (
    Add,
    Call,
    Const,
    GetGlobal,
    If,
    MatMul,
    Mul,
    Op,
    Return,
    Transpose,
    UnknownOp,
    Yield,
)
from niro.ir.program import (
    Block,
    Function,
    FunctionType,
    Global,
    Module,
    Region,
    SymbolName,
)
from niro.ir.types import Dimension, ScalarType, Shape, TensorType, Type
from niro.ir.values import Value, ValueId
from niro.ir.verify import (
    VerificationError,
    matmul_result_type,
    transpose_result_type,
    verify,
    verify_block_arguments,
    verify_call,
    verify_function_signature,
    verify_global,
    verify_op,
    verify_symbol_available,
    verify_terminator,
    verify_type,
    verify_value,
)

__all__ = [
    "Add",
    "AttributeName",
    "AttributeValue",
    "Attributes",
    "Block",
    "Call",
    "Const",
    "Dimension",
    "Function",
    "FunctionType",
    "GetGlobal",
    "Global",
    "If",
    "Literal",
    "MatMul",
    "Module",
    "Mul",
    "Op",
    "Region",
    "Return",
    "ScalarType",
    "Shape",
    "SymbolName",
    "TensorType",
    "Transpose",
    "Type",
    "UnknownOp",
    "Value",
    "ValueId",
    "VerificationError",
    "Yield",
    "matmul_result_type",
    "transpose_result_type",
    "verify",
    "verify_block_arguments",
    "verify_call",
    "verify_function_signature",
    "verify_global",
    "verify_op",
    "verify_symbol_available",
    "verify_terminator",
    "verify_type",
    "verify_value",
]
